#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
# set DPI for all future x sessions, currently disabled due to font and icon issues
# xrandr --output eDP --primary --mode 2256x1504 --dpi 150

# set DK layout
setxkbmap -layout dk

# start compositor
picom &

# start screengrabber 
flameshot &

# start notification centre 
dunst &

# start wallpaper and restore to previous wallpaper 
nitrogen --restore &

# start dwmblocks statusbar icons
slstatus &

# start window manager
exec dwm 
