#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#xrandr --output HDMI-0 --rotate right --left-of DP-0 
#xrandr --output DP-0 --rotate left --left-of DP-2 
#xrandr --output DP-2 --primary --right-of DP-0 
#/usr/bin/pipewire &
#/usr/bin/pipewire-pulse &
#/usb/bin/pipewire-media-session &

# set DK layout
setxkbmap -layout dk 

# start compositor
picom &

# start wallpaper and restore to previous wallpaper 
nitrogen --restore &

# start dwmblocks statusbar icons
dwmblocks &

# start window manager
exec dwm 
