exec-once=waybar -c ~/.config/mango/waybar/config.jsonc -s ~/.config/mango/waybar/style.css >/dev/null 2>&1 &
exec-once=swaybg -i ~/Pictures/wallpapers/fantasy-purple-landscape-sunset.jpg >/dev/null 2>&1 &

