#### Your post SUCKLESS starship to MODERNITY ####

# You need a terminal!
bind=SUPER,Return,spawn,alacritty
bind=SUPER,p,spawn,wmenu-run -l 10

# I am using comboview because I love to shill it.
# It works just like your normal view except
# If you continue the keycombo past the first number, you'll 
# view each subsequent tag with the first.
# If you don't like it just use view
bind=SUPER,1,comboview,1
bind=SUPER,2,comboview,2
bind=SUPER,3,comboview,3
bind=SUPER,4,comboview,4
bind=SUPER,5,comboview,5
bind=SUPER,6,comboview,6
bind=SUPER,7,comboview,7
bind=SUPER,8,comboview,8
bind=SUPER,9,comboview,9
bind=SUPER+CTRL,l,viewtoright
bind=SUPER+CTRL,h,viewtoleft

# switch window focus
bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev

# DWM style binds
bind=SUPER,i,incnmaster,+1
bind=SUPER,d,incnmaster,-1
bind=SUPER,h,setmfact,-0.05
bind=SUPER,l,setmfact,+0.05
bind=SUPER,z,zoom
bind=SUPER,code:59,focusmon,left
bind=SUPER,code:60,focusmon,right
bind=SUPER+SHIFT,code:59,tagmon,left,0
bind=SUPER+SHIFT,code:60,tagmon,right,0
bind=SUPER+SHIFT,w,killclient
bind=SUPER+SHIFT+CTRL,q,quit
bind=SUPER+SHIFT+CTRL,r,reload_config

# move windows around and move to tag
bind=SUPER+CTRL+SHIFT,1,tag,1
bind=SUPER+CTRL+SHIFT,2,tag,2
bind=SUPER+CTRL+SHIFT,3,tag,3
bind=SUPER+CTRL+SHIFT,4,tag,4
bind=SUPER+CTRL+SHIFT,5,tag,5
bind=SUPER+CTRL+SHIFT,6,tag,6
bind=SUPER+CTRL+SHIFT,7,tag,7
bind=SUPER+CTRL+SHIFT,8,tag,8
bind=SUPER+CTRL+SHIFT,9,tag,9
# silent move
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

# Unfortunately stack based exchange is still being worked on.
# take these lesser directional based ones. 
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# Mouse Button Bindings
# NONE mode key only work in ov mode
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_left,toggleoverview,-1
mousebind=NONE,btn_right,killclient,0

# screenshot
bind=SUPER+SHIFT,s,spawn,snip

# Layouts
# Layout binds are located in layouts.conf
