#### Your post SUCKLESS starship to MODERNITY ####
# waybar & wmenu required.
# These are defaults directly inspired by https://gist.github.com/erlendaakre/12eb90eef84a3ab81f7b531e516c9594
# Not everything is here, but there should be enough to get a feel for the config format.

# source all configurations from other locations
source=~/.config/mango/autostart.conf
source=~/.config/mango/env.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/visuals.conf
#source=~/.config/mango/rules.conf

