#### Your post SUCKLESS starship to MODERNITY ####
# waybar & wmenu required.
# These are defaults directly inspired by https://gist.github.com/erlendaakre/12eb90eef84a3ab81f7b531e516c9594
# Not everything is here, but there should be enough to get a feel for the config format.

# Layouts
circle_layouts=tile,monocle,scroller,grid,vertical_grid
bind=SUPER,t,setlayout,tile
bind=SUPER,f,togglefloating # Sorry no floating layouts
bind=SUPER,m,setlayout,monocle
bind=SUPER,g,setlayout,grid
bind=SUPER,s,setlayout,scroller
bind=SUPER+CTRL,code:60,switch_layout

# more layouts:
# vertical:vertical_tile,vertical_scroller,vertical_grid,vertical_monocle,vertical_spiral,vertical_dwindle
# Plus more being added
# Layouts in mango are per tag. So we'll set all tags to tile by default. 
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

