[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"

decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrainsMono NFP"
bold.family = "JetBrainsMono NFP"
italic.family = "JetBrainsMono NFP"
bold_italic.family = "JetBrainsMono NFP"
size = 8 
